[tool.poetry]
name = "komodoenv"
version = "0.1.0"
description = "Virtualenv, but for komodo releases"
authors = ["Zohar Malamant <zom@equinor.com>"]
license = "GPL-3.0"

[tool.poetry.scripts]
komodoenv = "komodoenv.main:main"

[tool.poetry.dependencies]
python = ">=3.6"
PyYaml = "^5.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
